# Site settings
title: ugur kuyumcular
email: ukymclr(dot)gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ugur.github.io" # the base hostname & protocol for your site
linkedin_username: ukymclr
github_username:  ugur

# Build settings
markdown: kramdown
